name: Build

on:
  push:
    branches: [main, zig-master]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build
        run: zig build -Doptimize=ReleaseSmall

      - name: Unit Test Ports
        run: |
          pushd port/gigadevice/gd32
          zig build test
          popd
          pushd port/nxp/lpc
          # TODO: Add tests
          # zig build test
          popd
          pushd port/raspberrypi/rp2xxx
          zig build test
          popd
          pushd port/stmicro/stm32
          zig build test
          popd

      - name: Build examples
        # TODO: Get this building from the root of the examples directory
        run: |
          pushd examples/gigadevice/gd32
          zig build
          popd
          pushd examples/nxp/lpc
          zig build
          popd
          pushd examples/raspberrypi/rp2xxx
          zig build
          popd
          pushd examples/stmicro/stm32
          zig build
          popd

      - name: Build Website
        run: zig build
        working-directory: website

      - name: Dry run packaging
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          MICROZIG_VERSION=$(zig build package -- get-version)
          echo microzig version: $MICROZIG_VERSION
          zig build package -- http://localhost:8000
          python3 -m http.server 8000 --directory boxzer-out &
          sleep 1

          cd tools/package-test
          zig fetch --save=microzig http://localhost:8000/${MICROZIG_VERSION}/microzig.tar.gz
          zig build -Doptimize=ReleaseSmall
          # zig build run-port-tests

          # clean up server
          jobs -p | xargs kill
